### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by fabien-michel** [Pierre-Sassoulas/django-zxcvbn-password-validator#18]
Hi,
I've installed `django-zxcvbn-password-validator` with pip and it work as expected.
There just a little strange issue: The french translation is not loaded.

I'm not sure to know why, may be it is is because the `.mo` file doesn't exists in your package ?

**Comment by fabien-michel** [comment]
I can reproduce the problem with the `exemple_project` in the repository.

```
git clone https://github.com/Pierre-Sassoulas/django-zxcvbn-password-validator.git
cd django-zxcvbn-password-validator/example_project
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
```

User password change in admin:
![2022-05-12_164243](https://user-images.githubusercontent.com/1167556/168102872-1424f46e-ed1e-42a3-9d2d-a94f7b56d76a.png)

**Comment by Pierre-Sassoulas** [comment]
Look like it's makemessages not compile message. https://code.djangoproject.com/ticket/24159 I used to launch both all the time.

**Comment by Pierre-Sassoulas** [comment]
Closing as answered and stale.

**Comment by Pierre-Sassoulas** [comment]
Does this answer your question https://github.com/Pierre-Sassoulas/django-zxcvbn-password-validator/issues/18#issuecomment-1125968959 ?

**Comment by fabien-michel** [comment]
I don't think a django third-party app require to have host project compile his translations.
Having a look to some django packages, they all embed the .mo file in the repo and the package.
https://github.com/encode/django-rest-framework/tree/master/rest_framework/locale/fr/LC_MESSAGES
https://github.com/django-cms/django-cms/tree/develop/cms/locale/fr/LC_MESSAGES

**Comment by Pierre-Sassoulas** [comment]
Right, rosetta wasn't doing that when I created the project in 2017. Feel free to open a merge request to add .mo to the packaging I'd merge it.
