### ISSUE TITLE
Problem with translations

### ISSUE THREAD

**Issue by andresmrm** [Pierre-Sassoulas/django-zxcvbn-password-validator#96]
Thanks again for the super fast MR review, merge and release! :smile: 

But the same problem I had when testing `example_project` (installing django-zxcvbn-password-validator with `pip -e .`) persists when using this package from my Django project (installing django-zxcvbn-password-validator version 1.4.4 from pip): changing `LANGUAGE_CODE` changes the entire Django admin, except for django-zxcvbn-password-validator strings, that stay in English.

![image](https://github.com/Pierre-Sassoulas/django-zxcvbn-password-validator/assets/937689/4d0b1fdb-2c56-43d7-b77b-3af7eaf6a9db)

I have these files in my Python environment related to this package (installed by pip):
```
django_zxcvbn_password_validator
├── __init__.py
├── settings.py
├── test_translate_zxcvbn_text.py
├── test_zxcvbn_password_validator.py
├── translate_zxcvbn_text.py
└── zxcvbn_password_validator.py
django_zxcvbn_password_validator-1.4.4.dist-info
├── INSTALLER
├── LICENSE
├── METADATA
├── RECORD
├── REQUESTED
├── top_level.txt
└── WHEEL
```
I also searched for `Utilisez un motif plus long sur le clavier` in this Python environment and couldn't find it. It appears to me the locale strings aren't been packaged.

**Comment by Pierre-Sassoulas** [comment]
Should be fixed in the released 1.4.5, thank you for opening the issue :)
